//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HONGLI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Item
    {
        public int Id { get; set; }
        public string OrderCode { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string ProductId { get; set; }
        public string ProductName { get; set; }
        public string ProductTitle { get; set; }
        public Nullable<decimal> ProductOriginalPrice { get; set; }
        public Nullable<decimal> ProductDealPrice { get; set; }
        public Nullable<int> Channel { get; set; }
        public Nullable<int> InsuranceLogo { get; set; }
        public string LicenseNo { get; set; }
    
        public virtual Order_Base Order_Base { get; set; }
    }
}
