//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HONGLI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Deliver
    {
        public int Id { get; set; }
        public string OrderCode { get; set; }
        public Nullable<int> DeliverType { get; set; }
        public string DeliverAddress { get; set; }
        public Nullable<System.DateTime> DeliverTime { get; set; }
        public Nullable<decimal> DeliverPrice { get; set; }
        public string DeliverName { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string DeliverMobile { get; set; }
        public string DeliverDistrictCode { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual Order_Base Order_Base { get; set; }
    }
}
