//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HONGLI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Base
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order_Base()
        {
            this.Order_Deliver = new HashSet<Order_Deliver>();
            this.Order_Pay = new HashSet<Order_Pay>();
            this.Order_PolicyHolder = new HashSet<Order_PolicyHolder>();
            this.Order_Item = new HashSet<Order_Item>();
        }
    
        public int Id { get; set; }
        public string OrderCode { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<decimal> AmountPayable { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> PaidAmount { get; set; }
        public Nullable<System.DateTime> PayTime { get; set; }
        public Nullable<int> Status { get; set; }
        public string TradeNo { get; set; }
        public Nullable<int> Channel { get; set; }
        public string UserId { get; set; }
        public string InvoiceTitle { get; set; }
        public Nullable<int> InvoiceType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Deliver> Order_Deliver { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Pay> Order_Pay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_PolicyHolder> Order_PolicyHolder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Item> Order_Item { get; set; }
    }
}
