//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HONGLI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Product
    {
        public int Id { get; set; }
        public string LicenseNo { get; set; }
        public string BrandModel { get; set; }
        public Nullable<decimal> TrafficCompulsoryInsurance { get; set; }
        public Nullable<decimal> TravelTax { get; set; }
        public Nullable<int> CompanyId { get; set; }
    }
}
