//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HONGLI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quote
    {
        public int Id { get; set; }
        public Nullable<decimal> TrafficCompulsoryInsurance { get; set; }
        public Nullable<decimal> TravelTax { get; set; }
        public Nullable<decimal> CommercialInsurance { get; set; }
        public Nullable<decimal> DamageInsurance { get; set; }
        public Nullable<decimal> ThirdpartyLiabilityInsurance { get; set; }
        public Nullable<decimal> SeatInsuranceDirver { get; set; }
        public Nullable<decimal> SeatInsurancePassenger { get; set; }
        public Nullable<decimal> TheftInsurance { get; set; }
        public Nullable<byte> CheckStatus { get; set; }
        public string CheckContent { get; set; }
        public Nullable<decimal> CommercialInsuranceRate { get; set; }
        public Nullable<decimal> CommercialInsuranceRateAmount { get; set; }
        public Nullable<decimal> TrafficCompulsoryInsuranceRate { get; set; }
        public Nullable<decimal> TrafficCompulsoryInsuranceRateAmount { get; set; }
        public Nullable<decimal> TravelTaxRate { get; set; }
        public Nullable<decimal> TravelTaxRateAmount { get; set; }
        public Nullable<decimal> SaveAmount { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> CouponAmount { get; set; }
        public string Memo { get; set; }
    }
}
